### ISSUE TITLE
[Bug]: Multiple main tags

### ISSUE THREAD

**Issue by sxppro** [tremorlabs/template-dashboard-oss#6]
### URL

/overview

### Bug description

There is a second `<main>` tag in `/overview` page, which is not present in the full dashboard template

### What is expected?

There generally be only one `<main>` tag, as per [HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element)

### What is actually happening?

A second `<main>` tag is being added in `(main)` layout, in addition to the one present in the root layout: https://github.com/tremorlabs/template-dashboard-oss/blob/c821ac4f5254bd541890e81232562ae5f57f8965/src/app/(main)/layout.tsx#L8

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### Any additional comments?

This issue does not appear to affect the full version, compare https://dashboard.tremor.so/overview and https://dashboard-oss.tremor.so/overview

**Comment by severinlandolt** [comment]
Pushed a fix!
